#pragma once
#include <stdint.h>
/* Existing T5 result numbers are preserved. RETAINED is additive. */
enum {
  RISC_STREAM_OK=0, RISC_STREAM_AGAIN=1, RISC_STREAM_EOF=2,
  RISC_STREAM_INVALID=-1, RISC_STREAM_DENIED=-2, RISC_STREAM_LIMIT=-3,
  RISC_STREAM_UNSUPPORTED=-4, RISC_STREAM_IO=-5,
  RISC_STREAM_DISCONNECTED=-6, RISC_STREAM_CANCELLED=-7,
  RISC_STREAM_BUSY=-8, RISC_STREAM_CLOSED=-9, RISC_STREAM_TIMEOUT=-10,
  RISC_STREAM_RETAINED=-11
};
enum { RISC_STREAM_READ=1, RISC_STREAM_WRITE=2 };
