// One end-to-end host scenario using the REAL signed stage, extractor,
// provenance verifier and directory transaction. The filesystem and durable
// floor are simulated; no claim is made about power loss or removable SD on a
// physical board. Real P-256 fixtures are generated by package_stage_test.py.
#define main original_stage_main
#include "package_archive_stage_test.cpp"
#undef main
#include "runtime/packages/PackageArchiveExtract.h"
#include "runtime/packages/PackageSignedProvenance.h"
#include "runtime/packages/PackageSignedTransaction.h"

#include <array>
#include <map>
#include <string>
#include <utility>

namespace {
constexpr PackageRuntimePolicy kPolicy{"xtensa-esp32s3", 2, 3,
                                       1024 * 1024, 4 * 1024 * 1024};
uint32_t resolve(const char* capability) {
  return std::strcmp(capability, "kernel.serial") == 0 ? 1u : 0u;
}
struct Floors {
  std::map<std::pair<unsigned, std::string>, uint32_t> records;
  bool failCommit = false;
  FloorRead read(Kind kind, const char* id, uint32_t& value) {
    value = 0;
    const auto it = records.find({static_cast<unsigned>(kind), id});
    if (it == records.end()) return FloorRead::NotEstablished;
    value = it->second;
    return FloorRead::Present;
  }
  FloorAdvance advance(Kind kind, const char* id, uint32_t value) {
    if (failCommit) return FloorAdvance::Unavailable;
    auto& current = records[{static_cast<unsigned>(kind), id}];
    if (value < current) return FloorAdvance::Downgrade;
    if (value == current) return FloorAdvance::AlreadyAtOrAbove;
    current = value;
    return FloorAdvance::Advanced;
  }
  uint32_t current() {
    uint32_t value = 0;
    assert(read(Kind::Driver, "gps-nmea", value) == FloorRead::Present);
    return value;
  }
};
struct Directory {
  std::map<std::string, std::vector<uint8_t>> files;
};
struct Disk {
  std::map<std::string, Directory> directories;
  SignedTransactionPaths paths{};
  Disk() { assert(signedTransactionPaths(Kind::Driver, "gps-nmea", paths)); }
  bool exists(const char* path) { return directories.count(path) != 0; }
  bool rename(const char* from, const char* to) {
    if (!exists(from) || exists(to)) return false;
    auto node = directories.extract(from);
    node.key() = to;
    directories.insert(std::move(node));
    return true;
  }
  bool purge(const char* path) {
    if (std::strcmp(path, paths.backup) || !exists(path)) return false;
    directories.erase(path); // Selective provenance-last purge has separate tests.
    return true;
  }
  bool verify(const char* path, const uint8_t* expected, PackageArchive& result,
              Floors& floors, Signer& signer, bool first) {
    result = {};
    if (std::strcmp(path, kSignedExtractStage) &&
        std::strcmp(path, paths.target) && std::strcmp(path, paths.backup)) return false;
    const auto it = directories.find(path);
    if (it == directories.end()) return false;
    const auto& files = it->second.files;
    const auto provenance = files.find(kPackageProvenanceName);
    if (provenance == files.end()) return false;
    const auto readProvenance = [&provenance](uint64_t offset, uint8_t* out, size_t count) {
      const auto& bytes = provenance->second;
      if (!out || offset > bytes.size() || count > bytes.size() - static_cast<size_t>(offset))
        return false;
      std::memcpy(out, bytes.data() + offset, count);
      return true;
    };
    const auto entrySize = [&files](const char* name, uint64_t& size) {
      const auto file = files.find(name);
      if (file == files.end()) return false;
      size = file->second.size();
      return true;
    };
    const auto readEntry = [&files](const char* name, uint64_t offset,
                                    uint8_t* out, size_t count) {
      const auto file = files.find(name);
      if (file == files.end() || !out || offset > file->second.size() ||
          count > file->second.size() - static_cast<size_t>(offset)) return false;
      std::memcpy(out, file->second.data() + offset, count);
      return true;
    };
    const auto exact = [&files](const PackageArchive& archive) {
      if (files.size() != static_cast<size_t>(archive.entryCount) + 1 ||
          files.count(kPackageProvenanceName) != 1) return false;
      for (size_t i = 0; i < archive.entryCount; ++i)
        if (files.count(archive.entries[i].name) != 1) return false;
      return true;
    };
    Sha256 hash;
    static PackageVerificationWorkspace workspace{};
    return verifySignedPackageDirectory(readProvenance, provenance->second.size(),
        entrySize, readEntry, exact, hash, signer, resolve,
        [&floors, first](const PackageArchive& archive) {
          return checkPackageSecurityFloor(floors, archive, first) == FloorCheck::Allowed;
        }, kPolicy, result, workspace, expected) ==
        ProvenanceResult::AuthenticatedDirectory &&
        result.identity.kind == Kind::Driver &&
        std::strcmp(result.identity.id, "gps-nmea") == 0;
  }
};
struct ExtractToDisk {
  Disk& disk;
  std::string active;
  bool owned = false;
  bool begin(const PackageArchive&) {
    owned = disk.directories.emplace(kSignedExtractStage, Directory{}).second;
    return owned;
  }
  bool beginEntry(const char* name, uint64_t length) {
    if (!owned || !safePackageEntryName(name) || !length) return false;
    active = name;
    return disk.directories.at(kSignedExtractStage).files.emplace(
        name, std::vector<uint8_t>{}).second;
  }
  bool append(const uint8_t* bytes, size_t count) {
    if (!owned || active.empty() || !bytes || !count) return false;
    auto& file = disk.directories.at(kSignedExtractStage).files.at(active);
    file.insert(file.end(), bytes, bytes + count);
    return true;
  }
  bool endEntry() { return owned && !active.empty(); }
  bool readEntry(const char* name, uint64_t offset, uint8_t* out, size_t count) {
    if (!owned || !name || !out || active != name) return false;
    const auto& bytes = disk.directories.at(kSignedExtractStage).files.at(name);
    if (offset > bytes.size() || count > bytes.size() - static_cast<size_t>(offset))
      return false;
    std::memcpy(out, bytes.data() + offset, count);
    return true;
  }
  bool writeProvenance(const uint8_t* prefix, size_t prefixLength,
                       const uint8_t* signature, size_t signatureLength) {
    if (!owned || !prefix || !signature) return false;
    auto& files = disk.directories.at(kSignedExtractStage).files;
    auto inserted = files.emplace(kPackageProvenanceName,
        std::vector<uint8_t>(prefix, prefix + prefixLength));
    if (!inserted.second) return false;
    inserted.first->second.insert(inserted.first->second.end(), signature,
                                  signature + signatureLength);
    return true;
  }
  bool seal() { return owned && !active.empty(); }
  bool discard() {
    if (owned) disk.directories.erase(kSignedExtractStage);
    owned = false;
    return true;
  }
};
using Fingerprint = std::array<uint8_t, 32>;
void prepare(Disk& disk, Floors& floors, Signer& signer,
             const std::vector<uint8_t>& bytes, PackageArchive& approved,
             Fingerprint& fingerprint, bool first) {
  assert(!disk.exists(kSignedExtractStage));
  auto source = bytes;
  const auto sourceRead = [&source](uint64_t at, uint8_t* out, size_t count) {
    if (!out || at > source.size() || count > source.size() - static_cast<size_t>(at))
      return false;
    std::memcpy(out, source.data() + at, count);
    return true;
  };
  Stage stage;
  stage.source = &source;
  Sha256 hash;
  static PackageVerificationWorkspace workspace{};
  assert(stageSignedPackageArchive(sourceRead, source.size(), stage, hash,
      signer, resolve, kPolicy, approved, workspace) ==
      ArchiveStageResult::ReadyForPublicationReview);
  assert(hash.start() &&
      hash.update(workspace.signedPrefix, static_cast<size_t>(approved.signatureOffset)) &&
      hash.finish(fingerprint.data()));
  const auto intakeRead = [&stage](uint64_t at, uint8_t* out, size_t count) {
    if (!out || at > stage.bytes.size() ||
        count > stage.bytes.size() - static_cast<size_t>(at)) return false;
    std::memcpy(out, stage.bytes.data() + at, count);
    return true;
  };
  ExtractToDisk destination{disk};
  PackageArchive extracted{};
  assert(extractSignedPackageArchive(intakeRead, stage.bytes.size(),
      fingerprint.data(), destination, hash, signer, resolve,
      [&floors, first](const PackageArchive& candidate) {
        return checkPackageSecurityFloor(floors, candidate, first) == FloorCheck::Allowed;
      }, kPolicy, extracted, workspace) ==
      ArchiveExtractResult::ReadyForPublicationReview);
  assert(samePackage(approved.identity, extracted.identity) &&
         approved.securityVersion == extracted.securityVersion);
  PackageArchive verified{};
  assert(disk.verify(kSignedExtractStage, fingerprint.data(), verified,
                     floors, signer, first));
}
SignedTransactionResult publish(Disk& disk, Floors& floors, Signer& signer,
    const PackageArchive& approved, const Fingerprint& expected, bool first = false) {
  PackageArchive observed{};
  const auto verify = [&](const char* path, const uint8_t* digest, PackageArchive& out) {
    return disk.verify(path, digest, out, floors, signer, first);
  };
  return publishSignedDirectoryTransaction(disk, approved, expected.data(), verify,
      [&](const char* path) { return disk.purge(path); }, floors, observed, first);
}
SignedTransactionResult recover(Disk& disk, Floors& floors, Signer& signer, bool first = false) {
  PackageArchive observed{};
  const auto verify = [&](const char* path, const uint8_t* digest, PackageArchive& out) {
    return disk.verify(path, digest, out, floors, signer, first);
  };
  return recoverSignedDirectoryTransaction(disk, Kind::Driver, "gps-nmea", verify,
      [&](const char* path) { return disk.purge(path); }, floors, observed, first);
}
} // namespace

int main(int argc, char** argv) {
  assert(argc == 4);
  const auto good = load(argv[1]);
  const auto upgrade = load(argv[2]);
  Signer signer(argv[3]);
  Disk disk;
  Floors floors;
  PackageArchive old{};
  Fingerprint oldFingerprint{};
  prepare(disk, floors, signer, good, old, oldFingerprint, true);
  assert(publish(disk, floors, signer, old, oldFingerprint) ==
         SignedTransactionResult::StageRejected); // Missing floor is not implicit enrollment.
  assert(publish(disk, floors, signer, old, oldFingerprint, true) ==
         SignedTransactionResult::Published);
  assert(floors.current() == 3 && disk.exists(disk.paths.target));
  assert(recover(disk, floors, signer) == SignedTransactionResult::VerifiedGeneration);

  // The reboot verifier reauthenticates genuine P-256 provenance and complete
  // on-disk payloads rather than trusting the earlier extraction decision.
  auto& installed = disk.directories.at(disk.paths.target).files;
  installed.at("driver.elf")[25] ^= 1;
  assert(recover(disk, floors, signer) == SignedTransactionResult::TargetRejected);
  installed.at("driver.elf")[25] ^= 1;
  installed.emplace("surprise.txt", std::vector<uint8_t>{1});
  assert(recover(disk, floors, signer) == SignedTransactionResult::TargetRejected);
  installed.erase("surprise.txt");
  installed.at(kPackageProvenanceName).back() ^= 1;
  assert(recover(disk, floors, signer) == SignedTransactionResult::TargetRejected);
  installed.at(kPackageProvenanceName).back() ^= 1;
  assert(recover(disk, floors, signer) == SignedTransactionResult::VerifiedGeneration);

  PackageArchive next{};
  Fingerprint nextFingerprint{};
  prepare(disk, floors, signer, upgrade, next, nextFingerprint, false);
  assert(next.securityVersion == 4 &&
         decidePackageVersion(next.identity, &old.identity) == InstallDecision::Upgrade);
  assert(systemPackageUseGate().pin(disk.paths.target));
  assert(publish(disk, floors, signer, next, nextFingerprint) ==
         SignedTransactionResult::InUse);
  assert(systemPackageUseGate().unpin(disk.paths.target));
  // Cut immediately after target->backup; the previous signed generation is
  // restored without advancing the durable floor and the stage is untouched.
  assert(disk.rename(disk.paths.target, disk.paths.backup));
  assert(recover(disk, floors, signer) == SignedTransactionResult::RecoveredGeneration);
  assert(floors.current() == 3 && disk.exists(kSignedExtractStage));
  // Cut after stage->target, before backup cleanup and NVS floor advancement.
  assert(disk.rename(disk.paths.target, disk.paths.backup));
  assert(disk.rename(kSignedExtractStage, disk.paths.target));
  assert(recover(disk, floors, signer) == SignedTransactionResult::VerifiedGeneration);
  assert(floors.current() == 4 && !disk.exists(disk.paths.backup));
  assert(recover(disk, floors, signer) == SignedTransactionResult::VerifiedGeneration);

  // Repeated package bytes must not bypass the monotonic floor even when
  // their old signature remains valid. No new stage is left after rejection.
  auto previous = good;
  auto previousRead = [&previous](uint64_t at, uint8_t* out, size_t count) {
    if (!out || at > previous.size() || count > previous.size() - static_cast<size_t>(at))
      return false;
    std::memcpy(out, previous.data() + at, count);
    return true;
  };
  ExtractToDisk refused{disk};
  Sha256 hash;
  static PackageVerificationWorkspace workspace{};
  PackageArchive rejected{};
  assert(extractSignedPackageArchive(previousRead, previous.size(),
      oldFingerprint.data(), refused, hash, signer, resolve,
      [&floors](const PackageArchive& candidate) {
        return checkPackageSecurityFloor(floors, candidate, false) == FloorCheck::Allowed;
      }, kPolicy, rejected, workspace) == ArchiveExtractResult::FloorRejected);
  assert(!disk.exists(kSignedExtractStage));
  std::puts("Signed end-to-end: real P-256 stage/extract/provenance, gated publish, reboot, tamper and rollback passed");
  return 0;
}
