/* x4pro-panel 0.2.0: split only to keep the provider implementation reviewable. */
#include "x4pro_panel_core.inc"
#include "x4pro_panel_uc_transport_1.inc"
#include "x4pro_panel_uc_transport_2.inc"
#include "x4pro_panel_uc_transport_3.inc"
#include "x4pro_panel_uc_profiles_1.inc"
#include "x4pro_panel_uc_profiles_2.inc"
#include "x4pro_panel_uc_profiles_3.inc"
#include "x4pro_panel_uc_profiles_4.inc"
#include "x4pro_panel_ssd1677_1.inc"
#include "x4pro_panel_ssd1677_2.inc"
#include "x4pro_panel_api_1.inc"
#include "x4pro_panel_api_2.inc"
#include "x4pro_panel_api_3.inc"
#include "x4pro_panel_api_4.inc"
