#!/usr/bin/env python3
"""Generate flash-only numeral scanlines from the repository's OFL Noto fonts.

Requires Pillow. No font files or rasterizer are needed on the device.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
HEIGHT = 224
out = ['// Generated by scripts/generate_clock_digits.py; do not edit.',
       '// Noto Sans / Noto Serif: SIL Open Font License, see builtinFonts/source.',
       '#pragma once', '#include <cstdint>', 'namespace DeskClockDigits {',
       'struct Span { uint8_t y, x, width; };',
       'struct Glyph { uint16_t start, count; uint8_t width; };',
       f'constexpr int height = {HEIGHT};']
for family in ('NotoSans', 'NotoSerif'):
    path = ROOT / f'lib/EpdFont/builtinFonts/source/{family}/{family}-Regular.ttf'
    font = ImageFont.truetype(str(path), 300)
    bounds = font.getbbox('0123456789:')
    spans, glyphs = [], []
    for char in '0123456789:':
        width = int(font.getlength(char) + 1)
        img = Image.new('L', (width, bounds[3] - bounds[1]), 255)
        ImageDraw.Draw(img).text((0, -bounds[1]), char, font=font, fill=0)
        img = img.resize((round(width * HEIGHT / img.height), HEIGHT), Image.Resampling.LANCZOS)
        assert img.width < 256
        start = len(spans)
        for y in range(HEIGHT):
            x = 0
            while x < img.width:
                if img.getpixel((x, y)) >= 128:
                    x += 1
                    continue
                left = x
                while x < img.width and img.getpixel((x, y)) < 128:
                    x += 1
                spans.append((y, left, x - left))
        glyphs.append((start, len(spans) - start, img.width))
    assert len(spans) < 65536
    out += [f'constexpr Span {family}Spans[] = {{']
    out += ['  ' + ','.join('{%d,%d,%d}' % p for p in spans[i:i+8]) + ',' for i in range(0, len(spans), 8)]
    out += ['};', f'constexpr Glyph {family}Glyphs[] = {{']
    out += ['  {%d,%d,%d},' % p for p in glyphs]
    out += ['};']
out += ['}  // namespace DeskClockDigits', '']
(ROOT / 'src/util/DeskClockDigits.h').write_text('\n'.join(out))
