#!/usr/bin/env python3
"""Generate a LOCAL, gitignored firmware public-key allowlist for signed MVP testing.

Only a public PEM is read. The private signer key MUST remain off-repository.
No key can be installed or authorized from an SD card or package metadata.
"""
import argparse
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
KINDS = {'application': 'Application', 'driver': 'Driver',
         'service': 'Service', 'provider': 'Provider'}


def decimal(text: str) -> int:
    if not text.isascii() or not text.isdecimal() or (len(text) > 1 and text[0] == '0'):
        raise argparse.ArgumentTypeError('use a positive canonical decimal integer')
    value = int(text)
    if not 0 < value <= 0xffffffff:
        raise argparse.ArgumentTypeError('expected positive uint32')
    return value


def package_id(text: str) -> str:
    if not 0 < len(text) < 64 or not text.isascii() or not text[0].isalnum() or not text[-1].isalnum():
        raise argparse.ArgumentTypeError('invalid canonical package ID')
    if any(c not in 'abcdefghijklmnopqrstuvwxyz0123456789_-' for c in text):
        raise argparse.ArgumentTypeError('package ID must be lowercase ASCII without traversal')
    return text


def point_from_public_pem(pem: Path) -> bytes:
    # SPKI DER for NIST P-256 ends in a BIT STRING containing one unused-bit
    # byte followed by the SEC1 uncompressed 65-byte public point.
    der = subprocess.run(['openssl', 'pkey', '-pubin', '-in', str(pem),
                          '-pubout', '-outform', 'DER'],
                         check=True, capture_output=True).stdout
    oid = bytes.fromhex('06082a8648ce3d030107')
    if oid not in der or len(der) < 70 or der[-68:-65] != b'\x03\x42\x00':
        raise ValueError('expected a valid uncompressed prime256v1 public PEM')
    point = der[-65:]
    if len(point) != 65 or point[0] != 4 or point[1:] == bytes(64):
        raise ValueError('invalid P-256 SEC1 public point')
    return point


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--public-key', type=Path, required=True)
    parser.add_argument('--kind', choices=KINDS, required=True)
    parser.add_argument('--package-id', type=package_id, required=True)
    parser.add_argument('--key-id', type=decimal, required=True)
    parser.add_argument('--min-security-version', type=decimal, required=True)
    parser.add_argument('--allow-first-install', action='store_true',
                        help='explicitly enroll this exact package identity')
    parser.add_argument('--output', type=Path,
                        default=ROOT / 'include/RiscRteLocalPackageTrust.h')
    args = parser.parse_args()
    point = point_from_public_pem(args.public_key)
    octets = ', '.join(f'0x{byte:02x}' for byte in point)
    first = 'true' if args.allow_first_install else 'false'
    header = f'''#pragma once
// LOCAL DEVELOPER PUBLIC KEY ONLY: generated by scripts/provision_mvp_package_signer.py.
// Never supply trust roots from SD/package metadata. Do not commit this header.
namespace RuntimePackages {{
inline MvpFirmwareTrust localMvpPackageTrust() {{
  static const uint8_t publicPoint[65] = {{{octets}}};
  static const TrustedPackageSigner allowed[] = {{
    {{{args.key_id}u, publicPoint, sizeof(publicPoint), Kind::{KINDS[args.kind]},
      "{args.package_id}", {args.min_security_version}u, false}}
  }};
  MvpFirmwareTrust trust{{}};
  trust.signers = allowed;
  trust.signerCount = 1;
  trust.allowFirstInstall = {first};
  return trust;
}}
}} // namespace RuntimePackages
'''
    args.output.parent.mkdir(parents=True, exist_ok=True)
    if args.output.exists():
        raise SystemExit(f'Refusing to overwrite existing local trust enrollment: {args.output}')
    args.output.write_text(header, encoding='utf-8')
    print(f'Wrote development PUBLIC key for {args.kind}:{args.package_id} to {args.output}')
    print('This key does not authorize execution, drivers, capabilities or production release.')


if __name__ == '__main__':
    main()
