#!/usr/bin/env python3
"""Stage independent ordinary X4 driver packages; never embed firmware bytes.

Consumes already-built, source-versioned ELF artifacts and uses the ordinary
package metadata/ZIP validator. This is a local artifact operation, not install.
"""
import hashlib
import json
from pathlib import Path
import shutil
from generate_provider_package_inputs_v1 import prepare
from pack_rte_zip import pack_directory

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ['platform_clock_v1', 'x4pro_panel', 'x4pro_buttons', 'x4pro_frontlight',
           'x4pro_sd', 'x4pro_i2c', 'x4pro_gt911', 'x4pro_battery', 'x4pro_rtc']

def stage(sources=SOURCES, board="xteink-x4-pro", output=None, omitted=()):
    output = output or ROOT / "dist/x4-independent-packages"
    output.mkdir(parents=True, exist_ok=True)
    records = []
    for name in sources:
        source = ROOT / 'Drivers' / name / 'manifest.json'
        manifest = json.loads(source.read_text())
        identity = manifest['id']
        built = ROOT / 'dist/experimental' / identity
        observed = json.loads((built / 'manifest.json').read_text())
        if any(observed.get(key) != value for key, value in manifest.items()):
            raise ValueError(f'Rebuild {identity}: artifact manifest differs from source')
        payload = (built / 'driver.elf').read_bytes()
        if observed.get('size_bytes') != len(payload) or observed.get('sha256') != hashlib.sha256(payload).hexdigest():
            raise ValueError(f'Rebuild {identity}: ELF custody mismatch')
        destination = output / identity
        if destination.exists():
            shutil.rmtree(destination)
        destination.mkdir()
        shutil.copyfile(built / 'driver.elf', destination / 'driver.elf')
        shutil.copyfile(source, destination / 'manifest.json')
        prepare(destination / 'driver.elf', source, destination)
        entries=[]
        for path in sorted(destination.iterdir()):
            data=path.read_bytes()
            entries.append(dict(name=path.name, size_bytes=len(data),
                                sha256=hashlib.sha256(data).hexdigest(),
                                executable=path.name=='driver.elf'))
        package=dict(schema=1, kind='driver', id=identity, version=manifest['version'],
                     artifact='driver.elf', architecture='xtensa-esp32s3', min_runtime_api=2,
                     entries=entries, requires=[dict(capability=r['capability'], min_api=r['api'])
                                                for r in manifest['requires']])
        (destination / '.package.json').write_text(json.dumps(package,separators=(',',':'))+'\n')
        archive=pack_directory(destination)
        filename=f"{identity}-{manifest['version']}.rte.zip"
        (output / filename).write_bytes(archive)
        records.append(dict(id=identity, version=manifest['version'], file=filename,
                            bytes=len(archive), sha256=hashlib.sha256(archive).hexdigest()))
    # SD-based boards keep every ordinary installed generation on the card.
    # No LittleFS/internal-flash image is generated by this staging route.
    legacy=output/'bootfs'
    if legacy.exists(): shutil.rmtree(legacy) # Retire only this builder's obsolete output.
    sdcard=output/'sdcard'
    if sdcard.exists(): shutil.rmtree(sdcard)
    (sdcard/'Drivers').mkdir(parents=True)
    (sdcard/'System/Config').mkdir(parents=True)
    (sdcard/'Packages/Inbox').mkdir(parents=True)
    selections=[]
    for record in records:
        shutil.copytree(output/record['id'],sdcard/'Drivers'/record['id'])
        shutil.copyfile(output/record['file'],sdcard/'Packages/Inbox'/record['file'])
        # The X4 default selects its complete physical driver set. The optional
        # omission hook remains for other board staging callers, but X4 passes
        # none so battery/RTC cannot silently fall back to lazy discovery.
        if record['id'] not in omitted:
            selections.append({'manifest':f"Drivers/{record['id']}/manifest.json"})
    (sdcard/'System/Config/boot.json').write_text(json.dumps(dict(
        board='System/Config/board.json',drivers=selections),indent=2)+'\n')
    (sdcard/'System/Config/board.json').write_text(json.dumps(dict(
        schema='riscrte.board-hardware',schema_version=1,board_id=board,
        revision='reader-profile',buses=[],devices=[]),indent=2)+'\n')
    (output/'artifacts.json').write_text(json.dumps(records,indent=2)+'\n')
    print(f'Staged and validated {len(records)} external packages in {output}')

if __name__ == '__main__':
    stage()
