#!/usr/bin/env python3
"""Distil the existing INT8 reconstruction + ordered dither teacher into a
compact categorical model. Inputs are four 3-bit intensity bins and Bayer phase.
No scene IDs, level geometry or runtime neural MACs. NumPy is offline only.
"""
import os
os.environ.setdefault('OPENBLAS_NUM_THREADS', '1')
import argparse, hashlib, json, re
from pathlib import Path
import numpy as np

SEED = 20260929

def weights(path, name, shape):
    body = re.search(r'ht_nn_' + name + r'\[[^=]+?=\s*(.*?);', path.read_text(), re.S)[1]
    return np.array(list(map(int, re.findall(r'-?\d+', body))), np.int32).reshape(shape)

def teacher(p, params):
    w1,b1,w2,b2=params
    h=np.maximum(0, ((p-128)@w1.T+b1+16)>>5)
    z=h@w2.T+b2
    r=np.clip(np.where(z>=0,(z+256)>>9,-((-z+256)>>9)),-127,127)
    a,b,c,d=p[:,4],p[:,5],p[:,7],p[:,8]
    base=np.stack(((a+b)//2,(a+c)//2,((a+b)//2+(c+d)//2)//2),axis=1)
    gate=np.ptp(p[:,[4,5,7,8]],axis=1)>=80
    r[~gate]=0
    return np.clip(base+r,0,255)

def patches(rng, per_bin):
    code=np.repeat(np.arange(4096), per_bin)
    bins=np.stack(((code>>9)&7,(code>>6)&7,(code>>3)&7,code&7),axis=1)
    corners=bins*32+rng.integers(0,32,bins.shape)
    a,b,c,d=corners.T
    # Extend local slopes, with independent perturbations and a minority of
    # unrelated neighbours to cover intersections and texture discontinuities.
    p=np.stack((3*a-b-c,2*a-c,2*b-d,2*a-b,a,b,2*c-d,c,d),axis=1)
    p+=rng.integers(-24,25,p.shape)
    random=rng.random(len(code))<.2
    p[random]=rng.integers(0,256,(random.sum(),9))
    p[:,[4,5,7,8]]=corners
    return code,np.clip(p,0,255).astype(np.int32)

def dots(values):
    e=np.array([[3,51,15,63],[35,19,47,31],[11,59,7,55],[43,27,39,23]])
    thresholds=np.stack((e+192,e+128,e+64),axis=-1).reshape(16,3)
    return values[:,None,:]>=thresholds[None,:,:]

def main():
    ap=argparse.ArgumentParser();ap.add_argument('--samples-per-bin',type=int,default=128)
    ap.add_argument('--out',type=Path,default=Path('Apps/hollow_trail_dither_model.inc'))
    ap.add_argument('--report',type=Path,default=Path('docs/HOLLOW_TRAIL_DITHER_MODEL.json'))
    args=ap.parse_args()
    if not 8<=args.samples_per_bin<=1024: ap.error('samples-per-bin must be 8..1024')
    source=Path('Apps/hollow_trail_neural_upscale.inc')
    params=[weights(source,n,s) for n,s in [('w1',(5,9)),('b1',(5,)),('w2',(3,5)),('b2',(3,))]]
    code,p=patches(np.random.default_rng(SEED),args.samples_per_bin)
    labels=dots(teacher(p,params))
    votes=labels.reshape(4096,args.samples_per_bin,16,3).sum(axis=1)
    learned=votes*2>=args.samples_per_bin
    words=np.zeros((4096,2),np.uint32)
    for phase in range(16):
        nibble=learned[:,phase,0].astype(np.uint32)+2*learned[:,phase,1]+4*learned[:,phase,2]
        words[:,phase//8]|=nibble.astype(np.uint32)<<((phase%8)*4)
    vc,vp=patches(np.random.default_rng(SEED+1),32)
    gold=dots(teacher(vp,params));prediction=learned[vc]
    gate=np.ptp(vp[:,[4,5,7,8]],axis=1)>=80
    report={'seed':SEED,'training_patches':len(code),'validation_patches':len(vc),
        'teacher_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),
        'model_bytes':words.nbytes,'validation_edge_dot_disagreement':float((gold[gate]!=prediction[gate]).mean()),
        'method':'Per-bin maximum-likelihood binary labels, independently for each Bayer phase and missing physical sample. Source anchor remains exact. Smooth patches use the existing packed path.',
        'data':'Random intensity bins, perturbed local slope extensions and independent neighbours; independent validation seed. No game scenes used for training.'}
    patterns,indices=np.unique(words,axis=0,return_inverse=True)
    report['expanded_model_bytes']=words.nbytes
    report['model_bytes']=patterns.nbytes+indices.size*2
    report['distinct_patterns']=len(patterns)
    text='/* Generated by scripts/train_hollow_trail_dither.py. Losslessly deduplicated\n * learned phase patterns. No runtime neural MACs. */\n'
    text+='static const uint16_t ht_dither_class[4096]={\n'
    text+=''.join(' '+','.join(map(str,indices[i:i+16]))+',\n' for i in range(0,4096,16))+'};\n'
    text+='static const uint32_t ht_dither_patterns[%d][2]={\n'%len(patterns)
    text+=''.join(' {0x%08xu,0x%08xu},\n'%tuple(row) for row in patterns)+'};\n'
    args.out.write_text(text);report['export_sha256']=hashlib.sha256(text.encode()).hexdigest()
    args.report.write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))
if __name__=='__main__':main()
