#!/usr/bin/env python3
"""Train/export Hollow Trail's learned deterministic halftone LUT.

This distills the existing clean bilinear + Bayer 8x8 output into a tiny lookup
model. Runtime inference is one table lookup per 480x270 logical source pixel;
there are no neural MACs, diffusion buffers, or full-resolution grayscale
surfaces.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

from train_hollow_trail_neural_upscale import synth_scene

SEED = 20260929
TRAIN_SCENES = 500
TRAIN_SAMPLES_PER_SCENE = 2000
VAL_SCENES = 100
VAL_SAMPLES_PER_SCENE = 2500

RANK = np.asarray([
    [0,48,12,60,3,51,15,63], [32,16,44,28,35,19,47,31],
    [8,56,4,52,11,59,7,55], [40,24,36,20,43,27,39,23],
    [2,50,14,62,1,49,13,61], [34,18,46,30,33,17,45,29],
    [10,58,6,54,9,57,5,53], [42,26,38,22,41,25,37,21],
], dtype=np.int16)


def black(darkness: int, x: int, y: int) -> int:
    return int(darkness > int(RANK[y & 7, x & 7]) * 4 + 2)


def teacher_pattern(image: np.ndarray, x: int, y: int) -> int:
    """Exact 2x2 physical block produced by the current bilinear+Bayer teacher."""
    h, w = image.shape
    xp, yp = min(x + 1, w - 1), min(y + 1, h - 1)
    a = int(image[y, x])
    right = int(image[y, xp])
    down = int(image[yp, x])
    down_right = int(image[yp, xp])
    horizontal = (a + right) // 2
    vertical = (a + down) // 2
    diagonal = (horizontal + ((down + down_right) // 2)) // 2
    px, py = 2 * x, 2 * y
    bits = (
        black(a, px, py),
        black(horizontal, px + 1, py),
        black(vertical, px, py + 1),
        black(diagonal, px + 1, py + 1),
    )
    return bits[0] | (bits[1] << 1) | (bits[2] << 2) | (bits[3] << 3)


def learn() -> np.ndarray:
    """Maximum-likelihood discrete classifier: 6-bit tone + 4x4 phase -> pattern."""
    counts = np.zeros((64, 16, 16), dtype=np.uint32)
    rng = np.random.default_rng(SEED)
    for _ in range(TRAIN_SCENES):
        image = synth_scene(rng)
        h, w = image.shape
        for index in rng.integers(0, h * w, size=TRAIN_SAMPLES_PER_SCENE):
            y, x = divmod(int(index), w)
            tone = int(image[y, x]) >> 2
            phase = (x & 3) | ((y & 3) << 2)
            counts[tone, phase, teacher_pattern(image, x, y)] += 1
    assert np.all(counts.sum(axis=-1) > 0)
    return counts.argmax(axis=-1).astype(np.uint8)


def validate(table: np.ndarray) -> dict[str, float | int]:
    rng = np.random.default_rng(SEED + 1)
    total = exact = correct_bits = density_error = 0
    for _ in range(VAL_SCENES):
        image = synth_scene(rng)
        h, w = image.shape
        for index in rng.integers(0, h * w, size=VAL_SAMPLES_PER_SCENE):
            y, x = divmod(int(index), w)
            predicted = int(table[int(image[y, x]) >> 2, (x & 3) | ((y & 3) << 2)])
            teacher = teacher_pattern(image, x, y)
            exact += predicted == teacher
            correct_bits += 4 - (predicted ^ teacher).bit_count()
            density_error += abs(predicted.bit_count() - teacher.bit_count())
            total += 1
    return {
        "seed": SEED,
        "training_samples": TRAIN_SCENES * TRAIN_SAMPLES_PER_SCENE,
        "validation_samples": total,
        "exact_pattern_agreement": exact / total,
        "dot_agreement": correct_bits / (4 * total),
        "mean_dot_count_error": density_error / total,
        "lut_bytes": int(table.size),
    }


def export_include(path: Path, table: np.ndarray, metrics: dict) -> None:
    values = table.reshape(-1)
    rows = []
    for start in range(0, len(values), 32):
        rows.append("    " + ", ".join(f"{int(v):2d}" for v in values[start:start+32]) + ",")
    text = f"""/* Auto-generated by scripts/train_hollow_trail_ai_dither.py.
 * Learned deterministic halftone classifier distilled from Hollow Trail's
 * clean bilinear + Bayer teacher. Runtime: one LUT lookup per logical pixel.
 * Seed {SEED}; training samples {metrics['training_samples']:,}.
 * Held-out: {metrics['exact_pattern_agreement']*100:.4f}% exact 2x2 pattern,
 * {metrics['dot_agreement']*100:.4f}% individual-dot agreement.
 */
#define HT_AI_DITHER_TONES 64
#define HT_AI_DITHER_PHASES 16
#define HT_AI_DITHER_LUT_SIZE (HT_AI_DITHER_TONES*HT_AI_DITHER_PHASES)

static const uint8_t ht_ai_dither_lut[HT_AI_DITHER_LUT_SIZE] = {{
{chr(10).join(rows)}
}};

static inline __attribute__((always_inline)) uint8_t ht_ai_dither_pattern(
        uint8_t darkness,unsigned x,unsigned y) {{
    unsigned tone=(unsigned)darkness>>2;
    unsigned phase=(x&3u)|((y&3u)<<2);
    return ht_ai_dither_lut[(tone<<4)|phase];
}}
"""
    path.write_text(text)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--export", type=Path)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()
    table = learn()
    metrics = validate(table)
    print(json.dumps(metrics, indent=2))
    if args.export:
        export_include(args.export, table, metrics)
    if args.report:
        args.report.write_text(json.dumps(metrics, indent=2) + "\n")


if __name__ == "__main__":
    main()
